export const CREATE_MASTER_COLUMN_PERMISSION = 'CREATE_MASTER_COLUMN_PERMISSION';
export const READ_MASTER_COLUMN_PERMISSION = 'READ_MASTER_COLUMN_PERMISSION';
export const UPDATE_MASTER_COLUMN_PERMISSION = 'UPDATE_MASTER_COLUMN_PERMISSION';
export const DELETE_MASTER_COLUMN_PERMISSION = 'DELETE_MASTER_COLUMN_PERMISSION';
export const FETCH_MASTER_COLUMN_PERMISSION = 'FETCH_MASTER_COLUMN_PERMISSION';
export const ERROR_MASTER_COLUMN_PERMISSION = 'ERROR_MASTER_COLUMN_PERMISSION';
