export const CREATE_MASTER_PASSWORD_RECOVERY = 'CREATE_MASTER_PASSWORD_RECOVERY';
export const READ_MASTER_PASSWORD_RECOVERY = 'READ_MASTER_PASSWORD_RECOVERY';
export const UPDATE_MASTER_PASSWORD_RECOVERY = 'UPDATE_MASTER_PASSWORD_RECOVERY';
export const DELETE_MASTER_PASSWORD_RECOVERY = 'DELETE_MASTER_PASSWORD_RECOVERY';
export const FETCH_MASTER_PASSWORD_RECOVERY = 'FETCH_MASTER_PASSWORD_RECOVERY';
export const ERROR_MASTER_PASSWORD_RECOVERY = 'ERROR_MASTER_PASSWORD_RECOVERY';
