export const CREATE_MASTER_MAIL_TEMPLATE = 'CREATE_MASTER_MAIL_TEMPLATE';
export const READ_MASTER_MAIL_TEMPLATE = 'READ_MASTER_MAIL_TEMPLATE';
export const UPDATE_MASTER_MAIL_TEMPLATE = 'UPDATE_MASTER_MAIL_TEMPLATE';
export const DELETE_MASTER_MAIL_TEMPLATE = 'DELETE_MASTER_MAIL_TEMPLATE';
export const FETCH_MASTER_MAIL_TEMPLATE = 'FETCH_MASTER_MAIL_TEMPLATE';
export const ERROR_MASTER_MAIL_TEMPLATE = 'ERROR_MASTER_MAIL_TEMPLATE';
