export const CREATE_MASTER_AUTHENTICATION = 'CREATE_MASTER_AUTHENTICATION';
export const READ_MASTER_AUTHENTICATION = 'READ_MASTER_AUTHENTICATION';
export const UPDATE_MASTER_AUTHENTICATION = 'UPDATE_MASTER_AUTHENTICATION';
export const DELETE_MASTER_AUTHENTICATION = 'DELETE_MASTER_AUTHENTICATION';
export const FETCH_MASTER_AUTHENTICATION = 'FETCH_MASTER_AUTHENTICATION';
export const ERROR_MASTER_AUTHENTICATION = 'ERROR_MASTER_AUTHENTICATION';
