export const CREATE_MASTER_RESOURCE = 'CREATE_MASTER_RESOURCE';
export const READ_MASTER_RESOURCE = 'READ_MASTER_RESOURCE';
export const UPDATE_MASTER_RESOURCE = 'UPDATE_MASTER_RESOURCE';
export const DELETE_MASTER_RESOURCE = 'DELETE_MASTER_RESOURCE';
export const FETCH_MASTER_RESOURCE = 'FETCH_MASTER_RESOURCE';
export const ERROR_MASTER_RESOURCE = 'ERROR_MASTER_RESOURCE';
