export const CREATE_PROJECT_PROJECT_STAGE = 'CREATE_PROJECT_PROJECT_STAGE';
export const READ_PROJECT_PROJECT_STAGE = 'READ_PROJECT_PROJECT_STAGE';
export const UPDATE_PROJECT_PROJECT_STAGE = 'UPDATE_PROJECT_PROJECT_STAGE';
export const DELETE_PROJECT_PROJECT_STAGE = 'DELETE_PROJECT_PROJECT_STAGE';
export const FETCH_PROJECT_PROJECT_STAGE = 'FETCH_PROJECT_PROJECT_STAGE';
export const ERROR_PROJECT_PROJECT_STAGE = 'ERROR_PROJECT_PROJECT_STAGE';
