export const CREATE_MASTER_TABLE_PERMISSION = 'CREATE_MASTER_TABLE_PERMISSION';
export const READ_MASTER_TABLE_PERMISSION = 'READ_MASTER_TABLE_PERMISSION';
export const UPDATE_MASTER_TABLE_PERMISSION = 'UPDATE_MASTER_TABLE_PERMISSION';
export const DELETE_MASTER_TABLE_PERMISSION = 'DELETE_MASTER_TABLE_PERMISSION';
export const FETCH_MASTER_TABLE_PERMISSION = 'FETCH_MASTER_TABLE_PERMISSION';
export const ERROR_MASTER_TABLE_PERMISSION = 'ERROR_MASTER_TABLE_PERMISSION';
