export const CREATE_MASTER_USER = 'CREATE_MASTER_USER';
export const READ_MASTER_USER = 'READ_MASTER_USER';
export const UPDATE_MASTER_USER = 'UPDATE_MASTER_USER';
export const DELETE_MASTER_USER = 'DELETE_MASTER_USER';
export const FETCH_MASTER_USER = 'FETCH_MASTER_USER';
export const ERROR_MASTER_USER = 'ERROR_MASTER_USER';
