export const CREATE_PROJECT_REQUIREMENT_TEST = 'CREATE_PROJECT_REQUIREMENT_TEST';
export const READ_PROJECT_REQUIREMENT_TEST = 'READ_PROJECT_REQUIREMENT_TEST';
export const UPDATE_PROJECT_REQUIREMENT_TEST = 'UPDATE_PROJECT_REQUIREMENT_TEST';
export const DELETE_PROJECT_REQUIREMENT_TEST = 'DELETE_PROJECT_REQUIREMENT_TEST';
export const FETCH_PROJECT_REQUIREMENT_TEST = 'FETCH_PROJECT_REQUIREMENT_TEST';
export const ERROR_PROJECT_REQUIREMENT_TEST = 'ERROR_PROJECT_REQUIREMENT_TEST';
