export const CREATE_MASTER_MAIL_CONFIRMATION = 'CREATE_MASTER_MAIL_CONFIRMATION';
export const READ_MASTER_MAIL_CONFIRMATION = 'READ_MASTER_MAIL_CONFIRMATION';
export const UPDATE_MASTER_MAIL_CONFIRMATION = 'UPDATE_MASTER_MAIL_CONFIRMATION';
export const DELETE_MASTER_MAIL_CONFIRMATION = 'DELETE_MASTER_MAIL_CONFIRMATION';
export const FETCH_MASTER_MAIL_CONFIRMATION = 'FETCH_MASTER_MAIL_CONFIRMATION';
export const ERROR_MASTER_MAIL_CONFIRMATION = 'ERROR_MASTER_MAIL_CONFIRMATION';
