export const CREATE_PROJECT_REQUIREMENTS_TYPES = 'CREATE_PROJECT_REQUIREMENTS_TYPES';
export const READ_PROJECT_REQUIREMENTS_TYPES = 'READ_PROJECT_REQUIREMENTS_TYPES';
export const UPDATE_PROJECT_REQUIREMENTS_TYPES = 'UPDATE_PROJECT_REQUIREMENTS_TYPES';
export const DELETE_PROJECT_REQUIREMENTS_TYPES = 'DELETE_PROJECT_REQUIREMENTS_TYPES';
export const FETCH_PROJECT_REQUIREMENTS_TYPES = 'FETCH_PROJECT_REQUIREMENTS_TYPES';
export const ERROR_PROJECT_REQUIREMENTS_TYPES = 'ERROR_PROJECT_REQUIREMENTS_TYPES';
