export const CREATE_MASTER_USER_GROUP = 'CREATE_MASTER_USER_GROUP';
export const READ_MASTER_USER_GROUP = 'READ_MASTER_USER_GROUP';
export const UPDATE_MASTER_USER_GROUP = 'UPDATE_MASTER_USER_GROUP';
export const DELETE_MASTER_USER_GROUP = 'DELETE_MASTER_USER_GROUP';
export const FETCH_MASTER_USER_GROUP = 'FETCH_MASTER_USER_GROUP';
export const ERROR_MASTER_USER_GROUP = 'ERROR_MASTER_USER_GROUP';
