export const CREATE_MASTER_ADDRESS = 'CREATE_MASTER_ADDRESS';
export const READ_MASTER_ADDRESS = 'READ_MASTER_ADDRESS';
export const UPDATE_MASTER_ADDRESS = 'UPDATE_MASTER_ADDRESS';
export const DELETE_MASTER_ADDRESS = 'DELETE_MASTER_ADDRESS';
export const FETCH_MASTER_ADDRESS = 'FETCH_MASTER_ADDRESS';
export const ERROR_MASTER_ADDRESS = 'ERROR_MASTER_ADDRESS';
