export const CREATE_PROJECT_PROJECT = 'CREATE_PROJECT_PROJECT';
export const READ_PROJECT_PROJECT = 'READ_PROJECT_PROJECT';
export const UPDATE_PROJECT_PROJECT = 'UPDATE_PROJECT_PROJECT';
export const DELETE_PROJECT_PROJECT = 'DELETE_PROJECT_PROJECT';
export const FETCH_PROJECT_PROJECT = 'FETCH_PROJECT_PROJECT';
export const ERROR_PROJECT_PROJECT = 'ERROR_PROJECT_PROJECT';
