export const CREATE_MASTER_MODEL_TABLE = 'CREATE_MASTER_MODEL_TABLE';
export const READ_MASTER_MODEL_TABLE = 'READ_MASTER_MODEL_TABLE';
export const UPDATE_MASTER_MODEL_TABLE = 'UPDATE_MASTER_MODEL_TABLE';
export const DELETE_MASTER_MODEL_TABLE = 'DELETE_MASTER_MODEL_TABLE';
export const FETCH_MASTER_MODEL_TABLE = 'FETCH_MASTER_MODEL_TABLE';
export const ERROR_MASTER_MODEL_TABLE = 'ERROR_MASTER_MODEL_TABLE';
