export const CREATE_MASTER_USER_GROUP_RESOURCE = 'CREATE_MASTER_USER_GROUP_RESOURCE';
export const READ_MASTER_USER_GROUP_RESOURCE = 'READ_MASTER_USER_GROUP_RESOURCE';
export const UPDATE_MASTER_USER_GROUP_RESOURCE = 'UPDATE_MASTER_USER_GROUP_RESOURCE';
export const DELETE_MASTER_USER_GROUP_RESOURCE = 'DELETE_MASTER_USER_GROUP_RESOURCE';
export const FETCH_MASTER_USER_GROUP_RESOURCE = 'FETCH_MASTER_USER_GROUP_RESOURCE';
export const ERROR_MASTER_USER_GROUP_RESOURCE = 'ERROR_MASTER_USER_GROUP_RESOURCE';
