export const CREATE_PROJECT_REQUIREMENT = 'CREATE_PROJECT_REQUIREMENT';
export const READ_PROJECT_REQUIREMENT = 'READ_PROJECT_REQUIREMENT';
export const UPDATE_PROJECT_REQUIREMENT = 'UPDATE_PROJECT_REQUIREMENT';
export const DELETE_PROJECT_REQUIREMENT = 'DELETE_PROJECT_REQUIREMENT';
export const FETCH_PROJECT_REQUIREMENT = 'FETCH_PROJECT_REQUIREMENT';
export const ERROR_PROJECT_REQUIREMENT = 'ERROR_PROJECT_REQUIREMENT';
